server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_board?serverTimezone=Asia/Seoul
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create #create update none
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

---

spring:
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            clientId: 1073085804262-5ik2cjma4soc692vkkct5v5qanqtse4r.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          naver:
            client-id: EAYpserNlN15cnzowC2O
            client-secret: 8gEQNfcAoH
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost/login/oauth2/code/naver  #네이버는 수정가능하나 규칙을 맞추자

          kakao:
            client-id: 3b5261251a7bb4e09841331127aafc3b
            clientSecret: FHMAwpnlgE92IIGN3E7pljFKDWr3JK9G
            redirectUri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #로그인창 보이기
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 정보 받을 곳
            user-name-attribute: response #회원정보를 json으로 받아올 때 response라는 키값으로 리턴.

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id